### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-repo-server#1]
Create self-signed certificate for nginx (for now)
Close direct ports 900x on firewall

**Comment by martinjoconnor** [comment]
Some notes from the Slack discussion:

http://security.stackexchange.com/questions/18684/how-to-implement-an-api-key-mechanism

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/AuthJavaSampleHMACSignature.html
